services:
  - type: web
    name: anjali-pg-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: CLIENT_URL
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FROM_NAME
        value: Anjali PG
      - key: FROM_EMAIL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: ADMIN_LOGIN_EMAIL
        value: admin@anjalipg.com
      - key: ADMIN_LOGIN_PASSWORD
        sync: false
